### ISSUE TITLE
Running on Inductive Datasets

### ISSUE THREAD

**Issue by HarryShomer** [LARS-research/AdaProp#1]
Hi,

Thanks for sharing the code!

I was hoping you could share how to run AdaProp on the inductive setting. The README seems to only refer to the transductive setting.

Thanks!

**Comment by AndrewZhou924** [comment]
Hi Harry, thanks for your interest in our work.

We have uploaded the code for inductive settings [here](https://github.com/LARS-research/AdaProp/tree/main/inductive).

You can download the code and use [reproduce.sh](https://github.com/LARS-research/AdaProp/blob/main/inductive/reproduce.sh) to run AdaProp.

**Comment by HarryShomer** [comment]
Thanks! I'll take a look.

**Comment by HarryShomer** [comment]
Hi Again!

Apologies for taking so long to run the code.

I found the following error when trying to run on the inductive setting. The same error is observed when trying to run any of the commands in `reproduce.sh`. Here's the traceback:

![Screenshot_20231013_172538](https://github.com/LARS-research/AdaProp/assets/25351167/da7c7a03-a6e1-4652-bacf-2a75e10f2238)

I was wondering if you might be able to lend me a hand in fixing this error.

Thanks!

Regards,
Harry

**Comment by AndrewZhou924** [comment]
Hi Harry,

Thanks for your feedback.

We reproduce your posted error with `numpy==1.24.3`.

To solve this error, you can degenerate it by `pip install numpy==1.21.6`.

Regards,
Zhanke

**Comment by HarryShomer** [comment]
Great, thanks!
