### ISSUE TITLE
运行时间

### ISSUE THREAD

**Issue by xiaoxingxing-x** [LARS-research/AdaProp#2]
我想问下作者在一张3090下，FB15k_237数据集上要训练多长时间？如果要在多张卡上运行，要改哪些地方？

**Comment by AndrewZhou924** [comment]
Hi. For sufficient training, it is recommended to train more than 100 epoches. You can also use the pre-trained weight for direct usage or fine-tuning. The model and data loader need to be updated if you want to conduct distributed training.
