### ISSUE TITLE
Take the liberty to ask about the performance of other data sets（WebQSP）

### ISSUE THREAD

**Issue by Biubiubiubo** [LARS-research/AdaProp#5]
Has this model been run on the WebQuestionSP dataset? If so, how effective? If not, can predecessors roughly estimate the performance of the model from the differences between the NELL data set and the WebQSP data set?

**Comment by AndrewZhou924** [comment]
Hi. We have not run the WebQuestionSP dataset yet. You are recommended to modify this code to fit your needs, and then you will get the empirical result.
