### ISSUE TITLE
About some questions in the paper

### ISSUE THREAD

**Issue by MavenZheng1003** [LARS-research/AdaProp#8]
It is mentioned in the paper that CompGCN and R-GCN are classified as Full-propagation, and the number of nodes involved in each message passing process is V, and V is the total number of all entities. I think it is not appropriate that the vector update formula mentioned in the CompGCN original paper is the aggregation of directly adjacent nodes according to the determined relationship. In this way, CompGCN seems to be more like the progressive propagation mentioned in your paper.
![Uploading 1718797885949.jpg…]()

**Comment by yzhangee** [comment]
I think what you mean is for a single-node update. In implementation, it updates all nodes on the graph. Even if a node is without neighbors, it will also be updated in the forward and backward processes.

**Comment by MavenZheng1003** [comment]
I am very interested in the work of your team, from Sum-GNN to RED-GNN to AdaProp, and I always hope to carry out some work on the basis of you. Thank you very much for your contribution and I hope to thank you in my own article in the near future!

**Comment by yzhangee** [comment]
Thank you for your interest in our group's work. Hope to see your work shortly!
