### ISSUE TITLE
The following problem occurs when I run the code and after debugging the problem is not solved. How can I fix it?

### ISSUE THREAD

**Issue by xiaowaiwaiA** [LARS-research/AdaProp#9]
The following problem occurs when I run the code and after debugging the problem is not solved. How can I fix it?
![1](https://github.com/user-attachments/assets/b30a2c6e-2f84-4e3c-ae11-e41f21ec8c2c)

**Comment by AndrewZhou924** [comment]
Hi, you should give the GPU index, e.g., `--gpu 0`.

**Comment by xiaowaiwaiA** [comment]
Thank you for your reply. I followed your instructions to execute the code, but it seems that it cannot accept the parameter --gpu 0.
![2](https://github.com/user-attachments/assets/43a51873-8bf8-4a8e-a256-3e39625e10d4)

**Comment by yzhangee** [comment]
You can directly set the gpu number at https://github.com/LARS-research/AdaProp/blob/159715c9950e67cea432859f9381cea617348a16/inductive/train.py#L32 as 0.

**Comment by xiaowaiwaiA** [comment]
Thank you very much! I've taken up too much of your time.
